### ISSUE TITLE
`TextEncoder`

### ISSUE THREAD

**Issue by jimmywarting** [nodejs/performance#51] opened 2023-02-04 13:17 UTC
> Here is my script that I have been using to test, annotated with the latest perf numbers I see on my computer with the different versions of node. Node v18 actually over doubled the performance of string encoding methods (awesome!), although it was across the board, so didn't really change the relative ranking. Node v19 seems to slightly regress in performance, but not a lot:
> ```js
> let u = new Uint8Array(2048);
> let b = Buffer.alloc(2048);
> let uf8Write = Buffer.prototype.utf8Write;
> let start = performance.now();
> let te = new TextEncoder();
> let result;
> for (let i = 0; i < 10000000; i++){
> 	//result = b.write('hello world', 10); // 78ns in v16, 32ns in v18, 36ns in v19
> 	//result = b.utf8Write('hello world', 10, 0xffffff); // 78ns in v16, 32ns in v18
> 	//result = uf8Write.call(u, 'hello world', 10, 0xffffff); // 90ns in v16, 42ns in v18
> 	//result = te.encodeInto('hello world', u.subarray(10)); // 146ns in v16, 57ns in v18, 60ns in v19
> 	// note that this is on par with buffer.write, but is useless since you can't specify a starting index, subarray time needs to be included in a fair comparison
> 	//result = te.encodeInto('hello world', u); // 79ns in v16, 33ns in v18
> }
> console.log(performance.now() - start, result);
> ```

_Originally posted by @kriszyp in https://github.com/kriszyp/cbor-x/issues/67#issuecomment-1408794006_

**Comment by anonrig** [comment] 2023-02-14 18:44
Here are my results:

```
> ~/Developer/node/out/Release/node ./text-encoder/index.mjs && bun run ./text-encoder/index.mjs && deno run -A ./text-encoder/deno.js

cpu: Apple M1 Max
runtime: node v20.0.0-pre (arm64-darwin)

benchmark                                     time (avg)             (min … max)       p75       p99      p995
-------------------------------------------------------------------------------- -----------------------------
buffer.write                               44.51 ns/iter     (44.2 ns … 55.1 ns)  44.25 ns  52.79 ns  53.61 ns
buffer.utf8Write                            45.4 ns/iter   (45.04 ns … 72.93 ns)  45.22 ns  51.05 ns  51.12 ns
utf8Write.call                             54.93 ns/iter   (52.84 ns … 66.25 ns)  56.08 ns  63.89 ns  64.44 ns
TextEncoder.encodeInto with subarray(10)   69.43 ns/iter    (66.82 ns … 91.3 ns)  70.57 ns  83.32 ns   85.6 ns
TextEncoder.encodeInto                     41.14 ns/iter   (39.08 ns … 52.39 ns)  42.68 ns  48.73 ns  49.78 ns
cpu: Apple M1 Max
runtime: bun 0.5.6 (arm64-darwin)

benchmark                                     time (avg)             (min … max)       p75       p99      p995
-------------------------------------------------------------------------------- -----------------------------
buffer.write                               11.98 ns/iter   (11.88 ns … 31.51 ns)  11.91 ns  13.83 ns  16.42 ns
buffer.utf8Write                           26.07 ns/iter   (23.23 ns … 36.62 ns)  26.36 ns  27.25 ns  27.55 ns
utf8Write.call                            error: undefined is not a function
utf8Write@[native code]
@/Users/yagiz/Developer/node-benchmarks/node_modules/.pnpm/mitata@0.1.6/node_modules/mitata/src/lib.mjs:36:19
asyncFunctionResume@[native code]
sync@/Users/yagiz/Developer/node-benchmarks/node_modules/.pnpm/mitata@0.1.6/node_modules/mitata/src/lib.mjs:23:28
@/Users/yagiz/Developer/node-benchmarks/node_modules/.pnpm/mitata@0.1.6/node_modules/mitata/src/cli.mjs:186:40
asyncFunctionResume@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
TextEncoder.encodeInto with subarray(10)   42.86 ns/iter  (36.54 ns … 462.84 ns)  37.56 ns 240.97 ns 282.04 ns
TextEncoder.encodeInto                     16.81 ns/iter  (15.67 ns … 235.89 ns)  16.04 ns  26.02 ns  72.45 ns
cpu: unknown
runtime: deno 1.30.3 (aarch64-apple-darwin)

benchmark                                     time (avg)             (min … max)       p75       p99      p995
-------------------------------------------------------------------------------- -----------------------------
buffer.write                               58.99 ns/iter   (56.56 ns … 90.89 ns)  60.76 ns   66.6 ns  67.34 ns
buffer.utf8Write                            52.8 ns/iter   (50.66 ns … 67.38 ns)  54.74 ns  58.16 ns  61.64 ns
utf8Write.call                             63.78 ns/iter  (61.03 ns … 104.87 ns)  65.25 ns  75.52 ns  93.36 ns
TextEncoder.encodeInto with subarray(10)   88.18 ns/iter  (85.89 ns … 102.64 ns)  90.18 ns  93.86 ns  94.91 ns
TextEncoder.encodeInto                     60.66 ns/iter   (59.83 ns … 73.75 ns)  60.17 ns   66.9 ns  68.59 ns
error: Uncaught TypeError: core.runMicrotasks is not a function
    core.runMicrotasks();
         ^
    at processTicksAndRejections (https://deno.land/std@0.153.0/node/_next_tick.ts:62:10)
    at https://deno.land/std@0.153.0/node/process.ts:312:7
    at innerInvokeEventListeners (internal:ext/web/02_event.js:776:9)
    at invokeEventListeners (internal:ext/web/02_event.js:816:7)
    at dispatch (internal:ext/web/02_event.js:685:11)
    at dispatchEvent (internal:ext/web/02_event.js:1066:14)
    at [internal:cli/worker.rs:90:39]:1:1
```

**Comment by anonrig** [comment] 2023-02-14 18:46
I don't see any regression, maybe I missed it but TextEncoder is quite fast. The issue is with using `subarray`. I'm going to close this since I think the results are pretty good and convincing (compared to previous versions of Node). But if you think there needs to be a specific performance improvement that needs to be done, please comment and we can reopen the issue.

**Closed by anonrig** 2023-02-14 18:46 UTC

**Comment by anonrig** [comment] 2023-02-14 18:48
For future reference, here's my benchmark code: https://github.com/anonrig/node-benchmarks/blob/main/text-encoder/index.mjs
