### ISSUE TITLE
WHATWG Streams

### ISSUE THREAD

**Issue by ronag** [nodejs/performance#9] opened 2022-11-14 18:03 UTC
WHATWG Streams are slow, and one of the primary reasons for slow performance with fetch in Node.

**Comment by mcollina** [comment] 2022-11-14 18:11
Every stream creates an Error, and creating errors is _slow_ in Node.js because of how we construct them. We also override the base types; I think we should not do that.

**Comment by RafaelGSS** [comment] 2022-11-14 18:17
Further info: https://github.com/nodejs/undici/issues/1203#issuecomment-1100969210

Every stream creates a `NodeError` which is slower the common `Error`: https://github.com/RafaelGSS/nodejs-bench-operations/blob/main/RESULTS-v18.md#nodejs-error

**Comment by anonrig** [comment] 2022-11-16 21:42
I'm going to work on this in the next couple of weeks.

@RafaelGSS Can you share where stream creates a `NodeError`? I couldn't find the path.
@mcollina Can you share the reference for `override the base types`?

**Comment by anonrig** [comment] 2022-11-21 23:21
I did a small perf change to ReadableStream (https://github.com/nodejs/node/pull/45489)

**Comment by ronag** [comment] 2022-11-22 07:09
> I did a small perf change to ReadableStream ([nodejs/node#45489](https://github.com/nodejs/node/pull/45489))

I think you are confusing Readable and ReadableStream. That PR has nothing to do with WHATWG streams as far as I can see.

**Comment by metcoder95** [comment] 2022-11-29 21:23
Please correct me if I'm wrong but are @RafaelGSS referring to these errors https://github.com/nodejs/node/blob/1bbd14eac20684a733250629c7896262c0ca4576/lib/internal/webstreams/readablestream.js#L33-L38?

An example from `RedeableStream` loads this set of errors, which are pre-constructed in https://github.com/nodejs/node/blob/1bbd14eac20684a733250629c7896262c0ca4576/lib/internal/errors.js.

If these are the errors, these should be somehow lazy-loaded or replaced by the common `Error` constructor?

**Comment by RafaelGSS** [comment] 2022-11-29 21:35
No. Actually, per spec when a default writable/readable is released an error should be propagated https://streams.spec.whatwg.org/#writable-stream-default-writer-release, and nowadays this is quite expensive. My initial analysis expands on this.

**Comment by RafaelGSS** [comment] 2022-11-29 21:36
Honestly, even changing to common Errors, we won't see much improvement.

**Comment by mcollina** [comment] 2022-11-29 22:38
Have you tried with the primoridial `Error`? https://github.com/nodejs/node/blob/1bbd14eac20684a733250629c7896262c0ca4576/lib/internal/errors.js#L27

**Comment by mcollina** [comment] 2022-11-30 20:31
The problem is not breaking the spec. We override all the Errors in node.. even the ones that we shouldn't.

**Comment by metcoder95** [comment] 2022-11-30 21:49
Noob question, but the `primordials` already contain the `TypeError` class, in theory, the spec specifies to just construct the `TypeError` and keep it until rejection if further validation fails. 

Can be used bypassing the call to https://github.com/nodejs/node/blob/1bbd14eac20684a733250629c7896262c0ca4576/lib/internal/errors.js#L360 and having at least **no** performance regression meanwhile respecting the spec, it or will have the same impact?
And subsequently, does the error has to have all the properties that the previous method attaches to it?

**Comment by RafaelGSS** [comment] 2022-12-15 21:30
Guys, It's on my radar. I'll be working on it when I have time.

Just created a benchmark PR https://github.com/nodejs/node/pull/45876.

**Comment by metcoder95** [comment] 2022-12-15 21:56
Are you planning to have some specific action items once the assessment? I’m more than happy to help you with if possible 🙂

**Comment by RafaelGSS** [comment] 2022-12-16 01:40
> Are you planning to have some specific action items once the assessment? I’m more than happy to help you with if possible 🙂

I'll try to collect some insights and post them here. Eventually, it can be a list of actionable

**Comment by RafaelGSS** [comment] 2023-01-03 19:17
So, I've spent some time on it again, and here's the summary:

- I'm using a local branch to perform those tests: https://github.com/RafaelGSS/node/tree/webstream-investigation
- I'm using `undici.fetch` as a real use case of web streams, the benchmark files are available at https://github.com/RafaelGSS/nodejs-webstreams-perf/blob/main/bench/fetch.js
- I did all the tests on my developer machine and on a dedicated server, and the results seem consistent.
- We can achieve a 30% of improvement in the Promise.reject + `NodeError` improvement. The following change bumps the performance by 30% https://github.com/RafaelGSS/node/commit/ecd6065cd2e06d518aac0ea23f900d299367f1f5
- For `each` fetch call, a `TransformStream` is created (which per se, creates a `WritableStream` and a `ReadableStream`) and all those are transferable objects.
- As previously mentioned in https://github.com/nodejs/undici/issues/1203#issuecomment-1101482629 and https://github.com/nodejs/node/issues/37080. `makeTransferable` is terrible for performance and after removing this call, we are able to achieve more 30% of improvement. See https://github.com/RafaelGSS/node/commit/e5e707bb94b9d0c728c2c98df572a4afdcbd944e.

I'll keep investigating other clear wins when I have time, but those two are great actionables.

**Comment by KhafraDev** [comment] 2023-01-12 20:15
ReadableStreamDefaultReader.releaseLock performance can be improved by only creating errors as needed:

<details>

<summary>diff</summary>

```diff
diff --git a/lib/internal/webstreams/readablestream.js b/lib/internal/webstreams/readablestream.js
index 5344785b90..18c86163c5 100644
--- a/lib/internal/webstreams/readablestream.js
+++ b/lib/internal/webstreams/readablestream.js
@@ -2029,15 +2029,22 @@ function readableStreamDefaultReaderRelease(reader) {
   readableStreamReaderGenericRelease(reader);
   readableStreamDefaultReaderErrorReadRequests(
     reader,
-    new ERR_INVALID_STATE.TypeError('Releasing reader')
+    'Releasing reader'
   );
 }

-function readableStreamDefaultReaderErrorReadRequests(reader, e) {
-  for (let n = 0; n < reader[kState].readRequests.length; ++n) {
-    reader[kState].readRequests[n][kError](e);
+function readableStreamDefaultReaderErrorReadRequests(reader, m) {
+  const { readRequests } = reader[kState];
+
+  if (readRequests.length) {
+    const error = new ERR_INVALID_STATE.TypeError(m);
+
+    for (let n = 0; n < readRequests.length; ++n) {
+      readRequests[n][kError](error);
-    reader[kState].readRequests[n][kError](e);
+function readableStreamDefaultReaderErrorReadRequests(reader, m) {
+  const { readRequests } = reader[kState];
+
+  if (readRequests.length) {
+    const error = new ERR_INVALID_STATE.TypeError(m);
+
+    for (let n = 0; n < readRequests.length; ++n) {
+      readRequests[n][kError](error);
+    }
+
+    readRequests.length = 0;
   }
-  reader[kState].readRequests = [];
 }

 function readableStreamBYOBReaderRelease(reader) {
```

</details>

For a simple use case, this no longer creates an error:

```js
const readable = getReadableOrSomething()

const reader = readable.getReader()
await reader.read()
reader.releaseLock()
```

Although I haven't benchmarked the code and haven't run any tests other than the WPTs (which all passed). I don't think releaseLock is a hot path either but it's the first thing I noticed while reading Rafael's comment above.

**Comment by RafaelGSS** [comment] 2023-01-13 03:23
@KhafraDev I think that might be a following up pr after https://github.com/nodejs/node/pull/46086, but instead of creating an error, re-use the one mentioned. But honestly, I don't think it will increase the performance because we're now re-using the errors.

**Comment by KhafraDev** [comment] 2023-01-13 05:07
I see that is just landed! I guess my solution is a viable alternative if there is an issue with re-using errors. 😄

**Closed** 2023-02-20 18:21 UTC
Labels: performance-agenda

**Comment by rluvaton** [comment] 2023-09-19 16:35
I have hunch it's related to a lot of promise creation (for example the ready promise on writable) node streams do not uses promises extensively IIRC
